PluginName: "§f§l[§c§lEssential§f§l]"

Title: '🔔§f'
Reloading: '🛠§f配置文件重载中...'
Reloaded: '🛠§f配置文件重载完成!'
OnlyPlayerUse: '🔔§f该指令仅限玩家输入'
NotPermission: '🔔§f你没有使用该指令的权限 §3%permission%'
OfflinePlayer: '🔔§f玩家§3%player%§f不在线或不存在'
SucceedSwitch: '🔔§f成功切换状态'

GroupAdd: '📗§f已被添加到权限组§3%group%§f，输入§3 /group§f查看更多信息'
PermissionAdd: '📗§f授予权限§3%permission%§f，输入§3 /group§f查看更多信息'
PrefixAdd: '📗§f授予头衔§3%prefix%§f，输入§3 /prefix§f查看更多信息'
PrefixChange: '📗§f修改头衔'

ShipApplyFor: '🎭§f已发送好友申请'
ShipAccept: '🎭§f已接受好友申请'
ShipExist: '🎭§f已经是对方的好友'

ItemRepair: '⚒§f手持物品耐久已修复'
ItemEnchant: '⚒§f手持物品添加附魔'

KitsNewPlayer: '🎁'

MaximumAmount: '🏡§f你已经设置了太多家了'
SucceedSettle: '🏡§f成功设置家§3%home%'
SucceedDelete: '🏡§f成功删除家§3%home%'
HaveNotSettle: '🏡§f没有设置家§3%home%'

HaveNotSetKit: '🔔§f工具包§3%kit%§f不存在'
DisposableKit: '🔔§f工具包§3%kit%§f只能使用一次'

ChatGlobal: '📢聊天范围切换为全部可见'
ChatNear: '📢聊天范围切换为附近可见'
ChatRoom: '📢已加入聊天室'

CooldownToUse: '⏳§f冷却中§3%time%'

HaveNotSetPoi: '🧿§f没有设置点§3%point%'
TeleportPoint: '🧿§f正在传送到§3%point%'
SavePoint: '🧿§f已保存返回点'
CancelWaiting: '🧿§f你取消了传送'
AlreadyHasTper: '🧿§f对方有一条未处理的申请'
SucceedSendTp: '🧿§f成功发出传送请求'
TeleportApply: '🧿§f玩家§3%player%§f请求传送到你身边'
TeleportIvttp: '🧿§f玩家§3%player%§f邀请你传送到他身边'
TpApplyRefuse: '🧿§f对方拒绝了你的请求'
ApplyRefuse: '🧿§f已拒绝传送请求'
ApplyAccept: '🧿§f已接受传送请求'

EconomyPlayer: '💰§3%player%§f拥有: §3%money%'

# 登录插件
Register: '👻§f欢迎加入我们，输入§3/reg [密码] §f注册一个账户吧'
DonRegister: '👻§f你还没有注册账户呢，输入§3/reg [密码] §f注册一个账户吧'
HasRegister: '👻§f抱歉，这个游戏名已经被别人抢先注册啦'
SucRegister: '👻§f成功注册账户，和大家交个朋友吧'
BlankPassword: '👻§f密码不能包含空格哦'
NamePassword: '👻§f你不能使用游戏名作为密码，因为容易被人盗号哦'
SimplePassword: '👻§f你的密码太简单啦，这样不安全的'
ShortPassword: '👻§f你的密码太短了，这样不安全的'
Login: '👻§f很高兴你再次回来，输入§3/l [密码] §f登录吧'
AutoLogin: '👻§f欢迎回来，已为您自动登录'
HasLogin: '👻§f你已经登录过啦，输入§3/account §f了解更多哦'
ErrorPassword: '👻§f密码错了，再重新输入吧,累计错误:§3%amount%'
ErrorTooMuch: '👻§f密码错误次数过多'
SucLogin: '👻§f成功登录，祝您游戏愉快'
DonLogin: '👻§f你还没有登录，输入§3/l [密码] §f登录吧'
SucChangePw: '👻§f成功修改密码'
RemindEmail: '👻§f输入§3/account email [邮箱] §f绑定邮箱吧!'
DonHasEmail: '👻§f该账号未绑定邮箱'
SucSetEmail: '👻§f成功设置邮箱'
InvalidEmail: '👻§f无效的邮箱'
SucSendEmail: '👻§f邮件已成功发送到§3%email%'
AlreadyProve: '👻§f你已经认证了邮箱'
NewPlayer: '👻§f欢迎新玩家§3%player%§f加入ヾ(•ω•`)o'
CommandError: '👻§f指令出错啦'
IllegalName: '游戏名仅限字母、数字和下划线哦'

Motd: '§f§m =  ==§b§l✧§e§l『§6§l边 缘 之 境§e§l』§b§l✧§f§m==  = §r        §b§emc.craftedge.cn   §3§l QQ群§f: §a§l643351215§7'
