Version: '${project.version}'
PluginName: "ยงfยงl[ยงcยงlEssentialยงfยงl]"

Title: '๐ยงf'
Reloading: 'ยงeยงl#ยงf้็ฝฎๆไปถ้่ฝฝไธญ...'
Reloaded: 'ยงeยงl#ยงf้็ฝฎๆไปถ้่ฝฝๅฎๆ!'
OnlyPlayerUse: 'ยงcยงl#ยงf่ฏฅๆไปคไป้็ฉๅฎถ่พๅฅ'
NotPermission: 'ยงcยงl#ยงfไฝๆฒกๆไฝฟ็จ่ฏฅๆไปค็ๆ้ ยง3%permission%'
OfflinePlayer: 'ยงcยงl#ยงf็ฉๅฎถยง3%player%ยงfไธๅจ็บฟๆไธๅญๅจ'
SucceedSwitch: 'ยงaยงl#ยงfๆๅๅๆข็ถๆ'
PluginLoad: 'ยงaยงl#ยงfๆๅๅ่ฝฝๆไปถยง3'
PluginEnable: 'ยงaยงl#ยงfๆๅๅฏ็จๆไปถยง3'
PluginEnableFail: 'ยง4ยงl#ยงfๆๆณๅฏ็จๆไปถยง3'
PluginDisable: 'ยงeยงl#ยงfๆๅๅณ้ญๆไปถยง3'
MotdMaintain: 'ยง4ยงl#ยงfๆๅกๅจ่ฎพ็ฝฎไธบ็ปดๆค็ถๆ'
MotdUpdate: 'ยงaยงl#ยงfๅทฒๆดๆฐmotd'

WorldClean: 'ๆๅกๅจๆธ็ๅ่ฎกๆถ'
WorldCreate: 'ยงeยงl#ยงfๆญฃๅจๅๅปบไธ็ยง3'
WorldUnload: 'ยงeยงl#ยงfๅธ่ฝฝไธ็ยง3'

GroupAdd: 'ยงaยงl#ยงfๅทฒ่ขซๆทปๅๅฐๆ้็ปยง3%group%ยงf๏ผ่พๅฅยง3 /groupยงfๆฅ็ๆดๅคไฟกๆฏ'
PermissionAdd: 'ยงaยงl#ยงfๆไบๆ้ยง3%permission%ยงf๏ผ่พๅฅยง3 /groupยงfๆฅ็ๆดๅคไฟกๆฏ'
PrefixAdd: 'ยงaยงl#ยงfๆไบๅคด่กยง3%prefix%ยงf๏ผ่พๅฅยง3 /prefixยงfๆฅ็ๆดๅคไฟกๆฏ'
PrefixChange: 'ยงeยงl#ยงfไฟฎๆนๅคด่ก'

ShipApplyFor: 'ยงbยงl#ยงfๅทฒๅ้ๅฅฝๅ็ณ่ฏท'
ShipAccept: 'ยงaยงl#ยงfๅทฒๆฅๅๅฅฝๅ็ณ่ฏท'
ShipExist: 'ยงcยงl#ยงfๅทฒ็ปๆฏๅฏนๆน็ๅฅฝๅ'
ShipNew: 'ยงbยงl#ยงfๆฅๆถๅฐๆฐ็ๅฅฝๅ่ฏทๆฑ'
ShipNull: 'ยงcยงl#ยงf่ฏทๅๅปบ็ซๅฅฝๅๅณ็ณป'
ShipUp: 'ยงbยงl#ยงfๅทฒๅ้ๅณ็ณปๅๆด่ฏทๆฑ'
ShipUpFail: 'ยงcยงl#ยงfๆๆณๆดๆนไบฒๅฏๅณ็ณป'
ShipUnknown: 'ยงcยงl#ยงfๆช็ฅๅณ็ณป'
ShipLimit: 'ยงcยงl#ยงfๅทฒ่พพๅฐ่ฏฅ็งๅณ็ณป็ๆๅคงๆฐ้'
ShipMaster: 'ยงbยงl#ยงfๅทฒๅ้ๆๅธ่ฏทๆฑ'
ShipApprentice: 'ยงbยงl#ยงfๅทฒๅ้ๆถๅพ้่ฏท'
ShipLover: 'ยงbยงl#ยงfๅทฒๅ้ไบคๅพ่ฏทๆฑ'
ShipCouple: 'ยงbยงl#ยงfๅทฒๅ้ๆฑๅฉ'
ShipRequestNull: 'ยง7ยงl#ยงfๆฒกๆ้่ฆๅค็็่ฏทๆฑ'
ShipRefuse: 'ยงeยงl#ยงfๅทฒๆ็ปๅฏนๆน่ฏทๆฑ'
ShipBreakIntimate: 'ยงeยงl#ยงfๅทฒๅณ่ฃไธบๆฎ้ๅฅฝๅ'
ShipBreak: 'ยงeยงl#ยงfๅทฒๆญ็ปๅฅฝๅๅณ็ณป'

ItemRepair: 'ยงaยงl#ยงfๆๆ็ฉๅ่ไนๅทฒไฟฎๅค'
ItemEnchant: 'ยงaยงl#ยงfๆๆ็ฉๅๆทปๅ้้ญ'

KitsNewPlayer: '๐'

MaximumAmount: 'ยงcยงl#ยงfไฝๅทฒ็ป่ฎพ็ฝฎไบๅคชๅคๅฎถไบ'
SucceedSettle: 'ยงaยงl#ยงfๆๅ่ฎพ็ฝฎๅฎถยง3%home%'
SucceedDelete: 'ยงeยงl#ยงfๆๅๅ้คๅฎถยง3%home%'
HaveNotSettle: 'ยงcยงl#ยงfๆฒกๆ่ฎพ็ฝฎๅฎถยง3%home%'

HaveNotSetKit: 'ยงcยงl#ยงfๅทฅๅทๅยง3%kit%ยงfไธๅญๅจ'
DisposableKit: 'ยงcยงl#ยงfๅทฅๅทๅยง3%kit%ยงfๅช่ฝไฝฟ็จไธๆฌก'
GiveKit: 'ยงaยงl#ยงfๅทฅๅทๅยง3%kit%ยงfๅทฒๅๆพ'

ChatGlobal: 'ยงaยงl#ยงf่ๅคฉ่ๅดๅๆขไธบๅจ้จๅฏ่ง'
ChatNear: 'ยงaยงl#ยงf่ๅคฉ่ๅดๅๆขไธบ้่ฟๅฏ่ง'
ChatRoom: 'ยงaยงl#ยงfๅทฒๅๅฅ่ๅคฉๅฎค'
ChatRoomFail: 'ยงcยงl#ยงfๅๅฅๅคฑ่ดฅ๏ผๅฏ็้่ฏฏ'

CooldownToUse: 'ยงcยงl#ยงfๅทๅดไธญยง3%time%'

HaveNotSetPoi: 'ยงcยงl#ยงfๆฒกๆ่ฎพ็ฝฎ็นยง3%point%'
TeleportPoint: 'ยงaยงl#ยงfๆญฃๅจไผ้ๅฐยง3%point%'
CancelWaiting: 'ยงeยงl#ยงfไฝๅๆถไบไผ้'
AlreadyHasTper: 'ยงcยงl#ยงfๅฏนๆนๆไธๆกๆชๅค็็็ณ่ฏท'
SucceedSendTp: 'ยงbยงl#ยงfๆๅๅๅบไผ้่ฏทๆฑ'
TeleportApply: 'ยงbยงl#ยงf็ฉๅฎถยง3%player%ยงf่ฏทๆฑไผ้ๅฐไฝ่บซ่พน'
TeleportIvttp: 'ยงbยงl#ยงf็ฉๅฎถยง3%player%ยงf้่ฏทไฝไผ้ๅฐไป่บซ่พน'
TpApplyRefuse: 'ยงcยงl#ยงfๅฏนๆนๆ็ปไบไฝ็่ฏทๆฑ'
ApplyRefuse: 'ยงeยงl#ยงfๅทฒๆ็ปไผ้่ฏทๆฑ'
ApplyAccept: 'ยงaยงl#ยงfๅทฒๆฅๅไผ้่ฏทๆฑ'

StructureCreateTip: 'ยงbยงl#ยงf่ง็นๅทฒๆธ้ค๏ผ่ฏทๅผๅง้ๆฉ็ฌฌไธไธช็น'
StructureCreateFirst: 'ยงaยงl#ยงfๆๅ้ๆฉ็ฌฌไธไธช็น ยง3%point%ยงf๏ผ่ฏทๆฅ็้ๆฉ็ฌฌไบไธช็น'
StructureCreateSecond: 'ยงaยงl#ยงfๆๅ้ๆฉ็ฌฌไบไธช็น ยง3%point%ยงf๏ผ่พๅฅ ยง3/structure create [name] ยงfๅฎๆๅๅปบ'
StructureCreateFinish: 'ยงaยงl#ยงfๅทฒๅๅปบ็ปๆ'
StructureCreateFail: 'ยงcยงl#ยงf่ๅด้ๆฉๅคฑ่ดฅ๏ผ่ฏท้ๆฐ้ๆฉ'
StructurePlaceFail: 'ยงcยงl#ยงf่ฏท้ๆฉๆๆๅปบ็ญๅฐ็น'
StructurePlaceNull: 'ยงcยงl#ยงfๅปบ็ญ็ปๆไฝไธๅญๅจ'
StructureLoad: 'ๆๅๅ่ฝฝ็ปๆไฝ%num%ไธช'

PlotCreate: 'ยงaยงl#ยงfๆๅๅๅปบๅฐ็ฎ ยง3'
PlotExist: 'ยงcยงl#ยงfๅๅ็งฐๅฐ็ฎๅทฒ็ปๅญๅจ'
PlotUpperLimit: 'ยงcยงl#ยงfๅทฒๅฐ่พพๆฐ้ไธ้'
PlotWorldUnknown: 'ยงcยงl#ยงfๆๆณๅจ่ฟไธชไธ็ๅๆๅฐ็ฎ'
PlotInDomain: 'ยงcยงl#ยงf่ฏฅๅบๅๅทฒ่ขซไปไบบๅ้ข'
PlotInLeague: 'ยงcยงl#ยงf่ฏฅๅบๅๅทฒ่ขซ่็ๅ้ข'
PlotServerProtect: 'ยงcยงl#ยงfๆๆณๅจๆๅกๅจไฟๆคๅบๅๅๅปบ'
PlotInRoad: 'ยงcยงl#ยงfๆๆณๅจ้่ทฏไธๅๅปบ'
PlotNonExistent: 'ยงcยงl#ยงfๅฐ็ฎไธๅญๅจ'
PlotNull: 'ยงeยงl#ยงfไฝ่ฟๆฒกๆๅฐ็ฎ'
PlotExpandNull: 'ยงcยงl#ยงf่ท็ฆป่ฆๆฉๅผ็ๅฐ็ฎ่ฟไบ้ฅ่ฟๆๅทฒๅ้ข'
PlotExpandFail: 'ยงcยงl#ยงf่ฟไบ้ป่ฟไปไบบๅฐ็ฎ'
PlotExpandCost: 'ยงcยงl#ยงfๆๆณๆฟๆๅฐ็ฎๆฉๅผ่ดน็จ ยง3'
PlotOutside: 'ยงeยงl#ยงf่ฏทๅจๅฐ็ฎๅๆง่กๆญคๆไฝ'
PlotForbid: 'ยงcยงl#ยงfไฝๆฒกๆๆ้่ฟๆทๅ'
PlotAbandonCenter: 'ยงcยงl#ยงfๅๅงๅฐ็ฎๆๆณๆๅผ'
PlotAbandon: 'ยงeยงl#ยงfๅฐ็ฎๅทฒ่ขซๆๅผ'
PlotRemove: 'ยงeยงl#ยงfๅฐ็ฎๅ้คๆๅ'
PlotGive: 'ยงeยงl#ยงfๅฐ็ฎ่ฝฌ่ฎฉๆๅ'
PlotBeGiven: 'ยงaยงl#ยงfๆฅๆถๅฐไปไบบ่ฝฌ่ฎฉ็ๅฐ็ฎ ยง3'
PlotPvp: 'ยงeยงl#ยงfๅบๅๅPVPๆชๅผๅฏ'
PlotProtectRoad: 'ยงcยงl#ยงf้่ทฏไฟๆค'
PlotProtectWorld: 'ยงcยงl#ยงfไธ็ไฟๆค'
PlotSetCenter: 'ยงaยงl#ยงfๅทฒ้ๆฐ่ฎพ็ฝฎไผ้็น'
PlotRename: 'ยงaยงl#ยงfๅทฒๆดๆฐๅฐ็ฎๅ็งฐ'
PlotFlag: 'ยงcยงl#ยงfไฝๆฒกๆๅฐ็ฎยง3%domain%ยงf็ยง3%flag%ยงfๆ้'
PlotFlagSwitch: 'ยงaยงl#ยงfๅฐ็ฎยง3%domain%ยงf็ยง3%flag%ยงfๆ้(%scope%)ๅๆขไธบ '
PlotEnter: 'ยงbยงl#ยงf่ฟๅฅๅฐ็ฎยง3%domain%ยงfๅฝๅฑไบยง3%player%'
PlotLeave: 'ยงbยงl#ยงf็ฆปๅผๅฐ็ฎยง3%domain%'
PlotReserve: ๅทฒๅฐๅฐ็ฎๅไธบๆๅกๅจไฟ็ๅฐ
PlotHelp: |
  ยงbยงl#ยงfๆยง3F3+Qยงfๅผๅฏๅบๅ่ๅดๆพ็คบ
  ยงbยงl#ยงfๅณ้ฎๅฐๅๅ้ขๅทฅๅทๅๅปบๅฐ็ฎๆๆฉๅผๅฐ็ฎ
  ยงbโ็งไบบๅๆ ยง6โ่็ๅๆ ยงcโๆๅกๅจๅๆ

CommandConfirm: 'ยงbยงl#ยงf่ฏทๅๆฌก่พๅฅๆไปค็กฎ่ฎค'
CommandArgument: 'ยงcยงl#ยงf่พๅฅ็ๆไปค็ผบๅฐๅฟ่ฆ็ๅๆฐ'

EconomyPlayer: 'ยงeยงl#ยง3%player%ยงfๆฅๆ: ยง3%money%'

# ็ปๅฝๆไปถ
Register: 'ยงbยงl#ยงfๆฌข่ฟๅๅฅๆไปฌ๏ผ่พๅฅยง3/reg [ๅฏ็] ยงfๆณจๅไธไธช่ดฆๆทๅง'
DonRegister: 'ยงbยงl#ยงfไฝ่ฟๆฒกๆๆณจๅ่ดฆๆทๅข๏ผ่พๅฅยง3/reg [ๅฏ็] ยงfๆณจๅไธไธช่ดฆๆทๅง'
HasRegister: 'ยงbยงl#ยงfๆฑๆญ๏ผ่ฟไธชๆธธๆๅๅทฒ็ป่ขซๅซไบบๆขๅๆณจๅๅฆ'
SucRegister: 'ยงaยงl#ยงfๆๅๆณจๅ่ดฆๆท๏ผๅๅคงๅฎถไบคไธชๆๅๅง'
BlankPassword: 'ยงcยงl#ยงfๅฏ็ไธ่ฝๅๅซ็ฉบๆผๅฆ'
NamePassword: 'ยงcยงl#ยงfไฝไธ่ฝไฝฟ็จๆธธๆๅไฝไธบๅฏ็๏ผๅไธบๅฎนๆ่ขซไบบ็ๅทๅฆ'
SimplePassword: 'ยงcยงl#ยงfไฝ็ๅฏ็ๅคช็ฎๅๅฆ๏ผ่ฟๆทไธๅฎๅจ็'
ShortPassword: 'ยงcยงl#ยงfไฝ็ๅฏ็ๅคช็ญไบ๏ผ่ฟๆทไธๅฎๅจ็'
Login: 'ยงbยงl#ยงfๅพ้ซๅดไฝๅๆฌกๅๆฅ๏ผ่พๅฅยง3/l [ๅฏ็] ยงf็ปๅฝๅง'
AutoLogin: 'ยงaยงl#ยงfๆฌข่ฟๅๆฅ๏ผๅทฒไธบๆจ่ชๅจ็ปๅฝ'
HasLogin: 'ยงeยงl#ยงfไฝๅทฒ็ป็ปๅฝ่ฟๅฆ๏ผ่พๅฅยง3/account ยงfไบ่งฃๆดๅคๅฆ'
ErrorPassword: 'ยงcยงl#ยงfๅฏ็้ไบ๏ผๅ้ๆฐ่พๅฅๅง,็ดฏ่ฎก้่ฏฏ:ยง3%amount%'
ErrorTooMuch: 'ยงcยงl#ยงfๅฏ็้่ฏฏๆฌกๆฐ่ฟๅค'
SucLogin: 'ยงaยงl#ยงfๆๅ็ปๅฝ๏ผ็ฅๆจๆธธๆๆๅฟซ'
DonLogin: 'ยงcยงl#ยงfไฝ่ฟๆฒกๆ็ปๅฝ๏ผ่พๅฅยง3/l [ๅฏ็] ยงf็ปๅฝๅง'
SucChangePw: 'ยงaยงl#ยงfๆๅไฟฎๆนๅฏ็'
RemindEmail: 'ยงbยงl#ยงf่พๅฅยง3/account email [้ฎ็ฎฑ] ยงf็ปๅฎ้ฎ็ฎฑๅง!'
DonHasEmail: 'ยงcยงl#ยงf่ฏฅ่ดฆๅทๆช็ปๅฎ้ฎ็ฎฑ'
SucSetEmail: 'ยงaยงl#ยงfๆๅ่ฎพ็ฝฎ้ฎ็ฎฑ'
InvalidEmail: 'ยงcยงl#ยงfๆๆ็้ฎ็ฎฑ'
SucSendEmail: 'ยงaยงl#ยงf้ฎไปถๅทฒๆๅๅ้ๅฐยง3%email%'
AlreadyProve: 'ยงeยงl#ยงfไฝๅทฒ็ป่ฎค่ฏไบ้ฎ็ฎฑ'
NewPlayer: 'ยงbยงl#ยงfๆฌข่ฟๆฐ็ฉๅฎถยง3%player%ยงfๅๅฅใพ(โขฯโข`)o'
CommandError: 'ยงcยงl#ยงfๆไปคๅบ้ๅฆ'
IllegalName: 'ๆธธๆๅไป้ๅญๆฏใๆฐๅญๅไธๅ็บฟๅฆ'

Motd: 'ยงfยงm =  ==ยงbยงlโงยงeยงlใยง6ยงl่พน ็ผ ไน ๅขยงeยงlใยงbยงlโงยงfยงm==  = ยงr        ยงbยงemc.craftedge.cn   ยง3ยงl QQ็พคยงf: ยงaยงl643351215ยง7'
