Debug: false

# 语言文件
Language: default

# SQL参数(高一点的版本需要在url加上'useSSL=false')
Sql: false
Url: 'jdbc:mysql://localhost:3306/mc_market?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'

###############################################
#
# 世界管理
#
###############################################
MainWorld: 'world'

# 火焰传播
IgniteSpread: false
# 火矢点然
IgniteArrow: false

# 开启结构体功能
StructureEnable: true

###############################################
#
# 好友关系
#
###############################################
MaxFriends: 50
MaxIntimate: 10