Debug: false

# 语言文件
Language: default

# SQL参数(高一点的版本需要在url加上'useSSL=false')
Sql: false
Url: 'jdbc:mysql://localhost:3306/mc_market?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'

DefaultPrefix: $<hg=#b2b9be:#5f7082>初来乍到
Website: "craftedge.cn"
ServerName: EdgeCraft

###############################################
#
# 世界管理
#
###############################################
MainWorld: 'world'

# 火焰传播
IgniteSpread: false
# 火矢点然
IgniteArrow: false

# 开启结构体功能
StructureEnable: true

# 最大领地数量和领地包含的最大区块数量
MaxDomain: 3
MaxChunk: 25
# 区块价格=基本价格+[(当前区块数量^2)*(基本价格/5)]
BaseChunkPrice: 300

###############################################
#
# 人际关系
#
###############################################
# 师傅数量和徒弟数量
MaxMaster: 1
MaxApprentice: 10

###############################################
#
# 经济
#
###############################################
# 基础经济
BaseMoney: 500
# 货币名称
CurrencyName: '§6ɞ'